
project_id = "jnfmuvtpdmwjemgoford"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[functions]
[functions.create-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true
